name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Test package compilation
        run: |
          python -c "import py_compile; py_compile.compile('sheetsight_py/__init__.py', doraise=True)"
          python -c "import py_compile; py_compile.compile('sheetsight_py/client.py', doraise=True)"
          python -c "import py_compile; py_compile.compile('sheetsight_py/types.py', doraise=True)"
          python -c "import py_compile; py_compile.compile('sheetsight_py/exceptions.py', doraise=True)"

      - name: Test package imports
        run: |
          pip install -e .
          python -c "import sheetsight_py; print('✅ Package imports successfully')"
          python -c "from sheetsight_py import SheetsightClient; print('✅ SheetsightClient imports successfully')"

      - name: Build package
        run: python -m build

      - name: Check package
        run: |
          pip install twine
          twine check dist/*
